<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0LUVACA" failures="1" tests="7" name="Personal Loan" time="0.086" errors="0" timestamp="2022-01-13T15:57:07 IST">
  <testcase classname="test.Tut1" name="Demo1" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Tut1.Demo1(Tut1.java:38)
at java.base/java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Demo1 -->
  <testcase classname="test.Tut1" name="Demo2" time="0.003"/>
  <testcase classname="test.Tut2" name="Demo3" time="0.005"/>
  <testcase classname="test.HomeLoan" name="GuestUserHome" time="0.001"/>
  <testcase classname="test.HomeLoan" name="MobileHomeLogin" time="0.001"/>
  <testcase classname="test.HomeLoan" name="MobileHomeSecond" time="0.002"/>
  <testcase classname="test.HomeLoan" name="WebHomeLogin" time="0.002"/>
</testsuite> <!-- Personal Loan -->
